version: "3"
services:
  github-proxy:
    container_name: github-proxy
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3005:3005"
    volumes:
      - ./:/app
  redis:
    container_name: redis
    image: redis:7.0.7-alpine
    ports:
      - "6379:6379"
  curler:
    container_name: curler
    image: yauritux/busybox-curl
    command: sleep 90000